INSERT INTO perfumes (name, brand, gender, budget, season, mood, notes, longevity_hours, inspired_by, alternative_suggestion) VALUES

-- MALE LUXURY
('Sauvage EDP', 'Dior', 'male', 'luxury', 'spring,summer,fall', 'daily,work,evening', 'fresh,spicy,citrus', 10, NULL, 'Prada Luna Rossa Carbon'),
('Bleu de Chanel', 'Chanel', 'male', 'luxury', 'spring,fall,winter', 'work,special,daily', 'woody,citrus,aromatic', 12, NULL, 'Missoni Parfum Pour Homme'),
('Aventus', 'Creed', 'male', 'luxury', 'spring,summer,fall', 'special,daily,work', 'fruity,woody,smoky', 12, NULL, 'Afnan Supremacy Silver'),
('Acqua di Gio Profumo', 'Giorgio Armani', 'male', 'luxury', 'spring,summer', 'daily,work', 'aquatic,woody,fresh', 9, NULL, 'Perry Ellis 360 Red'),
('Spicebomb Extreme', 'Viktor Rolf', 'male', 'luxury', 'fall,winter', 'evening,special', 'spicy,sweet,tobacco', 10, NULL, 'Bvlgari Man In Black'),
('Eros EDP', 'Versace', 'male', 'luxury', 'spring,fall,winter', 'evening,special,daily', 'sweet,vanilla,fresh', 9, NULL, 'Guess 1981 Los Angeles'),
('The One EDP', 'Dolce & Gabbana', 'male', 'luxury', 'fall,winter', 'evening,special', 'amber,spicy,tobacco', 7, NULL, 'Halloween Man Shot'),
('Y EDP', 'YSL', 'male', 'luxury', 'spring,fall,winter', 'work,evening,special', 'aromatic,fresh,woody', 10, NULL, 'Lattafa Fakhar Black'),
('Le Male', 'Jean Paul Gaultier', 'male', 'luxury', 'fall,winter', 'evening,daily,special', 'vanilla,powdery,fresh', 9, NULL, 'Cuba Gold'),
('Terre d Hermes', 'HERMES', 'male', 'luxury', 'spring,fall', 'work,daily', 'citrus,woody,spicy', 8, NULL, 'Rasasi Fattan'),
('Bottega Veneta Pour Homme', 'Bottega Veneta', 'male', 'luxury', 'fall,winter', 'work,special,evening', 'leather,woody,smoky', 9, NULL, 'Bentley For Men Absolute'),
('L Homme', 'YSL', 'male', 'luxury', 'spring,summer,fall', 'daily,work', 'citrus,spicy,woody', 8, NULL, 'Zara Seoul'),

-- MALE MID
('Club de Nuit Intense', 'Aramis', 'male', 'mid', 'spring,summer,fall', 'daily,special,work', 'fruity,woody,smoky', 9, 'Aventus - Creed', NULL),
('Explorer', 'MONTBLANC', 'male', 'mid', 'spring,summer,fall', 'work,daily', 'woody,citrus,aromatic', 7, 'Bleu de Chanel - Chanel', NULL),
('Boss Bottled', 'Hugo Boss', 'male', 'mid', 'spring,fall,winter', 'work,daily,special', 'woody,spicy,fruity', 7, NULL, 'Zara Man Gold'),
('Wanted', 'Azzaro', 'male', 'mid', 'spring,summer,fall', 'daily,work,evening', 'woody,spicy,citrus', 7, NULL, 'Invictus - Paco Rabanne'),
('Chrome', 'Azzaro', 'male', 'mid', 'spring,summer', 'daily,work', 'citrus,aquatic,fresh', 6, NULL, 'Nautica Voyage'),
('Polo Blue', 'Ralph Lauren', 'male', 'mid', 'spring,summer', 'daily,work,special', 'aquatic,fresh,woody', 7, NULL, 'Versace Pour Homme'),
('Polo Black', 'Ralph Lauren', 'male', 'mid', 'fall,winter', 'evening,special,daily', 'woody,spicy,sweet', 8, NULL, 'Lalique Encre Noire'),
('Pour Homme', 'Dsquared', 'male', 'mid', 'spring,fall', 'daily,work', 'woody,citrus,aromatic', 6, NULL, 'Zara Vibrant Leather Summer'),
('Fuel for Life', 'Diesel', 'male', 'mid', 'fall,winter', 'evening,special', 'woody,spicy,sweet', 7, NULL, 'Joop! Homme'),
('Joop Homme', 'Joop', 'male', 'mid', 'fall,winter', 'evening,special,daily', 'sweet,floral,woody', 8, NULL, 'Montblanc Individuel'),
('Guilty Pour Homme', 'Gucci', 'male', 'mid', 'fall,winter', 'evening,special', 'spicy,citrus,woody', 7, NULL, 'Antonio Banderas The Secret'),
('L Homme Ideal', 'Guerlain', 'male', 'mid', 'spring,fall', 'work,daily,special', 'woody,citrus,almond', 7, NULL, 'Zara 9.0'),
('Declaration', 'Cartier', 'male', 'mid', 'spring,fall', 'work,daily', 'woody,citrus,spicy', 7, NULL, 'Terre d Hermes - HERMES'),
('Kiton', 'Kiton', 'male', 'mid', 'spring,summer,fall', 'work,daily,special', 'citrus,woody,aromatic', 7, NULL, 'Fahrenheit - Dior'),
('John Varvatos', 'John Varvatos', 'male', 'mid', 'fall,winter', 'evening,special', 'woody,leather,spicy', 8, NULL, 'Burberry London'),
('Encre Noire', 'Lalique', 'male', 'mid', 'fall,winter', 'work,evening', 'woody,earthy,smoky', 8, NULL, 'Terre d Hermes - HERMES'),

-- MALE BUDGET
('Nautica Voyage', 'Nautica', 'male', 'budget', 'spring,summer', 'daily,work', 'aquatic,fresh,green', 5, 'Acqua di Gio - Giorgio Armani', NULL),
('Cool Water', 'Davidoff', 'male', 'budget', 'spring,summer', 'daily,work', 'aquatic,fresh,citrus', 5, 'Green Irish Tweed - Creed', NULL),
('Vibrant Leather', 'Zara', 'male', 'budget', 'spring,summer,fall', 'daily,work,special', 'citrus,woody,smoky', 4, 'Aventus Cologne - Creed', NULL),
('Dark Temptation', 'Axe', 'male', 'budget', 'fall,winter', 'evening,daily,special', 'sweet,chocolate,woody', 4, 'Black XS - Paco Rabanne', NULL),
('Blue Seduction', 'Antonio Banderas', 'male', 'budget', 'spring,summer', 'daily,work', 'aquatic,citrus,woody', 4, 'Versace Man Eau Fraiche', NULL),
('Seduction in Black', 'Antonio Banderas', 'male', 'budget', 'fall,winter', 'evening,special', 'spicy,woody,sweet', 5, 'La Nuit de l''Homme - YSL', NULL),
('The Golden Secret', 'Antonio Banderas', 'male', 'budget', 'spring,fall', 'daily,work,special', 'woody,spicy,citrus', 4, '1 Million - Paco Rabanne', NULL),
('Wanted', 'Hollister Co.', 'male', 'budget', 'spring,summer,fall', 'daily,special', 'fresh,woody,citrus', 4, 'Invictus - Paco Rabanne', NULL),
('Fierce', 'Abercrombie & Fitch', 'male', 'budget', 'spring,summer', 'daily,special', 'woody,citrus,fresh', 5, 'Platinum Egoiste - Chanel', NULL),
('SoCal', 'Hollister Co.', 'male', 'budget', 'summer,spring', 'daily,work', 'fresh,citrus,aquatic', 4, 'Clinique Happy', NULL),
('Pino Silvestre', 'Pino Silvestre', 'male', 'budget', 'fall,winter', 'daily,work', 'woody,green,fresh', 4, 'Polo Green - Ralph Lauren', NULL),
('Police To Be', 'Police', 'male', 'budget', 'fall,winter', 'daily,evening', 'woody,spicy,fresh', 4, 'Le Male - JPG', NULL),
('Ferrari Black', 'Ferrari', 'male', 'budget', 'fall,winter', 'daily,work,evening', 'spicy,woody,citrus', 4, 'Boss Bottled - Hugo Boss', NULL),
('Desigual Fresh', 'Desigual', 'male', 'budget', 'spring,summer', 'daily,work', 'fresh,citrus,woody', 4, 'CK One - Calvin Klein', NULL),
('Iceberg Twice', 'Iceberg', 'male', 'budget', 'spring,summer,fall', 'daily,work', 'citrus,fresh,woody', 4, 'L Eau d Issey - Issey Miyake', NULL),

-- FEMALE LUXURY
('Coco Mademoiselle', 'CHANEL', 'female', 'luxury', 'spring,fall,winter', 'work,special,daily', 'citrus,floral,patchouli', 12, NULL, 'Armaf Club de Nuit Woman'),
('Black Opium', 'YSL', 'female', 'luxury', 'fall,winter', 'evening,special', 'sweet,vanilla,coffee', 10, NULL, 'Zara Gardenia'),
('La Vie Est Belle', 'Lancome', 'female', 'luxury', 'fall,winter', 'special,evening', 'sweet,fruity,vanilla', 10, NULL, 'Zara Rose Gourmand'),
('Libre Intense', 'YSL', 'female', 'luxury', 'fall,winter', 'evening,work,special', 'floral,vanilla,lavender', 10, NULL, 'Zara Golden Decade'),
('Good Girl', 'Carolina Herrera', 'female', 'luxury', 'fall,winter', 'evening,special', 'sweet,floral,spicy', 10, NULL, 'Zara Deep Garden'),
('Delina', 'Rabanne', 'female', 'luxury', 'spring,summer', 'special,evening,daily', 'floral,fruity,rose', 10, NULL, 'Lattafa Yara'),
('J adore', 'Dior', 'female', 'luxury', 'spring,summer', 'work,daily', 'floral,fruity,fresh', 8, NULL, 'Zara Rose'),
('Chloe EDP', 'Chloe', 'female', 'luxury', 'spring,summer', 'daily,work', 'floral,fresh,rose', 8, NULL, 'Cute - La Rive'),
('Alien', 'Thierry Mugler', 'female', 'luxury', 'fall,winter', 'evening,special', 'floral,woody,amber', 12, NULL, 'Zara Violet Blossom'),
('L Interdit', 'Givenchy', 'female', 'luxury', 'fall,winter', 'evening,special', 'floral,woody,sweet', 9, NULL, 'Zara Luminous'),
('Miss Dior', 'Dior', 'female', 'luxury', 'spring,summer', 'daily,work,special', 'floral,fresh,rose', 9, NULL, 'Zara Nude Bouquet'),
('Chance EDP', 'CHANEL', 'female', 'luxury', 'spring,summer,fall', 'special,daily,evening', 'floral,fruity,citrus', 9, NULL, 'Zara Applejuice'),
('My Way', 'Gior Armani', 'female', 'luxury', 'spring,summer,fall', 'daily,work,special', 'floral,woody,citrus', 9, NULL, 'Zara Sublime Epoque'),
('Flowerbomb', 'Viktor Rolf', 'female', 'luxury', 'fall,winter,spring', 'special,evening,daily', 'floral,sweet,patchouli', 11, NULL, 'Zara Oriental'),

-- FEMALE MID
('Chance Eau Tendre', 'CHANEL', 'female', 'mid', 'spring,summer,fall', 'daily,work,special', 'floral,fruity,citrus', 7, NULL, 'Zara Applejuice'),
('Idole', 'Lancome', 'female', 'mid', 'spring,summer,fall,winter', 'daily,work,evening,special', 'floral,rose,woody', 8, NULL, 'Lattafa Mayar'),
('Bombshell', 'Victoria Secret', 'female', 'mid', 'spring,summer', 'daily,special', 'fruity,floral,fresh', 6, NULL, 'Zara Orchid'),
('Daisy', 'Marc Jacobs', 'female', 'mid', 'spring,summer', 'daily,work', 'floral,fresh,fruity', 7, NULL, 'Avon Eve Truth'),
('Good Girl Blush', 'Carolina Herrera', 'female', 'mid', 'spring,summer,fall', 'daily,special,evening', 'floral,fruity,sweet', 8, NULL, 'Lattafa Yara Tous'),
('Cloud', 'Ariana Grande', 'female', 'mid', 'fall,winter,spring', 'daily,evening,special', 'sweet,vanilla,floral', 6, 'Baccarat Rouge 540 - MFK', NULL),
('Gucci Bloom', 'Gucci', 'female', 'mid', 'spring,summer', 'daily,work,special', 'floral,white flowers', 8, NULL, 'Diptyque Do Son'),
('Flora Gorgeous Gardenia', 'Gucci', 'female', 'mid', 'spring,summer,fall', 'daily,work,special', 'fruity,floral,sweet', 7, NULL, 'Viva La Juicy - Juicy Couture'),
('Viva La Juicy', 'Juicy Couture', 'female', 'mid', 'fall,winter', 'evening,special,daily', 'sweet,fruity,floral', 8, NULL, 'Victoria Secret Tease'),
('Daisy Love', 'Marc Jacobs', 'female', 'mid', 'spring,summer,fall', 'daily,work', 'floral,musky,sweet', 7, NULL, 'Zara Femme'),
('Si EDP', 'Giorgio Armani', 'female', 'mid', 'fall,winter', 'work,special,evening', 'floral,fruity,woody', 9, NULL, 'La Rive In Woman'),
('Eros Pour Femme', 'Versace', 'female', 'mid', 'spring,summer', 'daily,work,special', 'floral,citrus,fresh', 7, NULL, 'Zara Rose'),
('Lolita Lempicka', 'Lolita Lempicka', 'female', 'mid', 'fall,winter', 'evening,special', 'sweet,floral,anise', 9, NULL, 'Guerlain La Petite Robe Noire'),
('Guilty Pour Femme', 'Gucci', 'female', 'mid', 'fall,winter', 'evening,special', 'floral,spicy,woody', 8, NULL, 'Zara Deep Garden'),
('Escada Joyful', 'Escada', 'female', 'mid', 'spring,summer', 'daily,work,special', 'fruity,floral,fresh', 6, NULL, 'Zara Applejuice'),
('Elie Saab Le Parfum', 'Elie Saab', 'female', 'mid', 'spring,fall,winter', 'special,evening,work', 'floral,woody,honey', 9, NULL, 'Zara Rose'),

-- FEMALE BUDGET
('Applejuice', 'Zara', 'female', 'budget', 'spring,summer', 'daily,work', 'floral,fruity,fresh', 4, 'Chance Eau Tendre - Chanel', NULL),
('Femme', 'Zara', 'female', 'budget', 'fall,winter', 'daily,work,evening', 'vanilla,powdery,floral', 5, 'Miracle - Lancome', NULL),
('Red Temptation', 'Zara', 'female', 'budget', 'fall,winter,spring', 'evening,special', 'sweet,amber,woody', 7, 'Baccarat Rouge 540 - MFK', NULL),
('Golden Decade', 'Zara', 'female', 'budget', 'fall,winter', 'work,evening,special', 'floral,vanilla', 6, 'Libre Intense - YSL', NULL),
('Rose Gourmand', 'Zara', 'female', 'budget', 'fall,winter', 'evening,special', 'rose,vanilla,sweet', 7, 'Roses Vanille - Mancera', NULL),
('Gardenia', 'Zara', 'female', 'budget', 'fall,winter,spring', 'evening,special,daily', 'floral,sweet,woody', 5, 'Black Opium - YSL', NULL),
('Violet Blossom', 'Zara', 'female', 'budget', 'fall,winter', 'evening,special', 'floral,violet,woody', 5, 'Alien - Thierry Mugler', NULL),
('Deep Garden', 'Zara', 'female', 'budget', 'spring,fall', 'daily,work,evening', 'green,floral,woody', 5, 'Good Girl - Carolina Herrera', NULL),
('Luminous', 'Zara', 'female', 'budget', 'spring,summer', 'daily,work,special', 'fresh,floral,citrus', 4, 'L Interdit - Givenchy', NULL),
('Rose', 'Zara', 'female', 'budget', 'spring,summer,fall', 'daily,work,special', 'rose,floral,fresh', 4, 'J adore - Dior', NULL),
('Orchid', 'Zara', 'female', 'budget', 'spring,summer', 'daily,special', 'floral,sweet,fruity', 4, 'Bombshell - Victoria Secret', NULL),
('Vanilla', 'Zara', 'female', 'budget', 'fall,winter', 'daily,evening,special', 'sweet,vanilla,floral', 5, 'Hypnotic Poison - Dior', NULL),
('Fantasy', 'Britney Spears', 'female', 'budget', 'fall,winter', 'daily,evening', 'sweet,fruity,gourmand', 6, 'Pink Sugar - Aquolina', NULL),
('My Secret', 'Halloween', 'female', 'budget', 'spring,summer', 'daily,work', 'floral,citrus,fresh', 4, 'Amor Amor - Cacharel', NULL),
('Desigual Fresh', 'Desigual', 'female', 'budget', 'spring,summer', 'daily,work', 'fresh,citrus,floral', 4, 'Light Blue - Dolce & Gabbana', NULL),
('Iceberg Twice', 'Iceberg', 'female', 'budget', 'spring,summer', 'daily,work', 'floral,fruity,fresh', 4, 'Daisy - Marc Jacobs', NULL),

-- UNISEX LUXURY
('Baccarat Rouge 540', 'Maison Francis Kurkdjian', 'unisex', 'luxury', 'fall,winter,spring', 'special,evening,work', 'sweet,spicy,woody,amber', 12, NULL, 'Zara Red Temptation'),
('Tobacco Vanille', 'Tom Ford', 'unisex', 'luxury', 'fall,winter', 'evening,special', 'sweet,spicy,tobacco,vanilla', 12, NULL, 'Zara Tobacco Collection'),
('Santal 33', 'Le Labo', 'unisex', 'luxury', 'spring,fall,winter', 'work,daily,special', 'woody,powdery,leather', 10, NULL, 'Zara Energetically New York'),
('Jazz Club', 'Maison Margiela', 'unisex', 'luxury', 'fall,winter', 'evening,special', 'sweet,woody,tobacco', 8, NULL, 'Lattafa Ameer Al Oudh'),
('By the Fireplace', 'Maison Margiela', 'unisex', 'luxury', 'fall,winter', 'evening,special,daily', 'woody,sweet,smoky', 9, NULL, 'Zara Ebony Wood'),
('Wood Sage and Sea Salt', 'Jo Malone', 'unisex', 'luxury', 'spring,summer,fall', 'daily,work', 'aquatic,woody,fresh', 5, NULL, 'Jenny Glow Wood & Sage'),
('Angels Share', 'Kilian', 'unisex', 'luxury', 'fall,winter', 'evening,special', 'sweet,woody,spicy', 10, NULL, 'Lattafa Khamrah'),
('Silver Mountain Water', 'Creed', 'unisex', 'luxury', 'spring,winter,fall', 'work,daily,special', 'aquatic,citrus,tea', 11, NULL, 'Armaf Club de Nuit Sillage'),
('Erba Pura', 'Xerjoff', 'unisex', 'luxury', 'spring,summer,fall', 'special,daily,work', 'fruity,sweet,citrus', 12, NULL, 'Lattafa Ana Abiyedh Rouge'),
('Lost Cherry', 'Tom Ford', 'unisex', 'luxury', 'fall,winter,spring', 'evening,special,daily', 'sweet,cherry,woody', 9, NULL, 'Zara Cherry Smoothie'),
('Oud Wood', 'Tom Ford', 'unisex', 'luxury', 'fall,winter', 'evening,special,work', 'woody,spicy,smoky', 10, NULL, 'Versace Oud Noir'),
('Molecule 02', 'Escentric Molecules', 'unisex', 'luxury', 'spring,summer,fall,winter', 'daily,work,special', 'woody,musky,citrus', 10, NULL, 'Juliette Has A Gun Not A Perfume'),

-- UNISEX MID
('Molecule 01', 'Escentric Molecules', 'unisex', 'mid', 'spring,summer,fall,winter', 'daily,work,special,evening', 'woody,musky', 9, NULL, 'Zara Blanc a Porter'),
('CK One', 'Calvin Klein', 'unisex', 'mid', 'spring,summer', 'daily,work', 'citrus,fresh,green', 5, NULL, 'Azzaro Chrome'),
('CK Be', 'Calvin Klein', 'unisex', 'mid', 'spring,summer,fall', 'daily,work,special', 'citrus,musk,woody', 6, NULL, 'Prada Luna Rossa'),
('Eternity', 'Calvin Klein', 'unisex', 'mid', 'spring,summer,fall', 'daily,work,special', 'floral,citrus,musk', 7, NULL, 'Paco Rabanne XS'),
('Ocean Leather', 'Memo Paris', 'unisex', 'mid', 'fall,winter,spring', 'work,special,evening', 'leather,aquatic,woody', 9, NULL, 'Tom Ford Ombre Leather'),
('L Eau d Issey', 'Issey Miyake', 'unisex', 'mid', 'spring,summer', 'daily,work', 'aquatic,floral,woody', 6, NULL, 'Zara Aqua'),
('A Men', 'Thierry Mugler', 'unisex', 'mid', 'fall,winter', 'evening,special', 'sweet,spicy,woody', 9, NULL, 'Rochas Man'),
('Alien Man', 'Thierry Mugler', 'unisex', 'mid', 'fall,winter', 'evening,special,work', 'woody,spicy,amber', 8, NULL, 'Bvlgari Man In Black'),
('Kenzo Homme', 'Kenzo', 'unisex', 'mid', 'spring,summer,fall', 'daily,work', 'woody,aquatic,fresh', 7, NULL, 'Joop Jump'),
('L Eau Par Kenzo', 'Kenzo', 'unisex', 'mid', 'spring,summer', 'daily,work', 'aquatic,fresh,floral', 6, NULL, 'Desigual Fresh Unisex'),
('Iceberg Twice', 'Iceberg', 'unisex', 'mid', 'spring,summer,fall', 'daily,work,special', 'citrus,fresh,floral', 6, NULL, 'CK One - Calvin Klein'),
('Jil Sander Sun', 'Jil Sander', 'unisex', 'mid', 'spring,summer', 'daily,work,special', 'citrus,floral,woody', 6, NULL, 'Nivea Sun'),

-- UNISEX BUDGET
('Aqua', 'Zara', 'unisex', 'budget', 'spring,summer', 'daily,work', 'aquatic,fresh,citrus', 4, 'Silver Mountain Water - Creed', NULL),
('Ebony Wood', 'Zara', 'unisex', 'budget', 'fall,winter', 'daily,evening,special', 'woody,spicy,sweet', 6, 'Wood Sage and Sea Salt - Jo Malone', NULL),
('Warm Leather', 'Zara', 'unisex', 'budget', 'fall,winter', 'evening,special,daily', 'leather,woody,spicy', 6, 'Jazz Club - Maison Margiela', NULL),
('Cherry Smoothie', 'Zara', 'unisex', 'budget', 'fall,winter,spring', 'evening,special,daily', 'sweet,cherry,fruity', 5, 'Lost Cherry - Tom Ford', NULL),
('Waterlily', 'Zara', 'unisex', 'budget', 'spring,summer', 'daily,work', 'floral,aquatic,fresh', 4, 'Gucci Bloom - Gucci', NULL),
('Energetically New York', 'Zara', 'unisex', 'budget', 'spring,summer,fall,winter', 'daily,work,special', 'woody,musky,fresh', 6, 'Santal 33 - Le Labo', NULL),
('Cool', 'Davidoff', 'unisex', 'budget', 'spring,summer', 'daily,work', 'aquatic,fresh,green', 5, 'Neroli Portofino - Tom Ford', NULL),
('Iceberg Twice Ice', 'Iceberg', 'unisex', 'budget', 'spring,summer', 'daily,work', 'citrus,fresh,aquatic', 4, 'CK One - Calvin Klein', NULL),
('Joop Jump', 'Joop', 'unisex', 'budget', 'spring,fall', 'daily,work,special', 'citrus,woody,fresh', 5, 'Allure Homme Sport - Chanel', NULL),
('Police To Be', 'Police', 'unisex', 'budget', 'fall,winter', 'daily,evening,special', 'woody,spicy,sweet', 4, 'Halloween Man', NULL),
('Desigual Fresh Unisex', 'Desigual', 'unisex', 'budget', 'spring,summer', 'daily,work', 'fresh,citrus,floral', 4, 'L Eau Par Kenzo - Kenzo', NULL);