INSERT INTO perfumes (name, brand, gender, budget, season, mood, longevity_hours, inspired_by, alternative_suggestion) VALUES
('Sauvage', 'Dior', 'male', 'luxury', 'summer', 'daily', 10, NULL, 'Axe Dark Temptation'),
('Bleu de Chanel', 'Chanel', 'male', 'luxury', 'winter', 'work', 12, NULL, 'Zara Vibrant Leather'),
('Aventus', 'Creed', 'male', 'luxury', 'spring', 'special', 12, NULL, 'Armaf Club de Nuit'),
('Y Eau de Parfum', 'YSL', 'male', 'luxury', 'fall', 'evening', 9, NULL, 'Zara Vibrant Leather'),
('Acqua di Gio', 'Giorgio Armani', 'male', 'luxury', 'summer', 'daily', 8, NULL, 'Nautica Voyage'),
('Dark Temptation', 'Axe', 'male', 'budget', 'winter', 'evening', 4, 'Sauvage - Dior', NULL),
('Vibrant Leather', 'Zara', 'male', 'budget', 'winter', 'work', 5, 'Bleu de Chanel - Chanel', NULL),
('Club de Nuit Intense', 'Armaf', 'male', 'mid', 'spring', 'special', 8, NULL, NULL),
('Nautica Voyage', 'Nautica', 'male', 'budget', 'summer', 'daily', 5, 'Acqua di Gio - Giorgio Armani', NULL),
('Legend', 'Mont Blanc', 'male', 'mid', 'fall', 'work', 7, NULL, NULL),
('Coco Mademoiselle', 'Chanel', 'female', 'luxury', 'fall', 'evening', 12, NULL, 'Zara Femme'),
('La Vie Est Belle', 'Lancome', 'female', 'luxury', 'winter', 'special', 10, NULL, 'Oriflame Feminelle'),
('Black Opium', 'YSL', 'female', 'luxury', 'winter', 'evening', 10, NULL, 'Zara Black Peony'),
('Flowerbomb', 'Viktor&Rolf', 'female', 'luxury', 'spring', 'special', 11, NULL, 'Victoria Secret Bombshell'),
('Daisy', 'Marc Jacobs', 'female', 'luxury', 'spring', 'daily', 7, NULL, 'Zara Femme'),
('Zara Femme', 'Zara', 'female', 'budget', 'fall', 'evening', 4, 'Coco Mademoiselle - Chanel', NULL),
('Feminelle', 'Oriflame', 'female', 'budget', 'winter', 'special', 5, 'La Vie Est Belle - Lancome', NULL),
('Black Peony', 'Zara', 'female', 'budget', 'winter', 'evening', 4, 'Black Opium - YSL', NULL),
('Bombshell', 'Victoria Secret', 'female', 'mid', 'spring', 'special', 7, NULL, NULL),
('Libre', 'YSL', 'female', 'luxury', 'summer', 'work', 9, NULL, 'Zara Femme'),
('CK One', 'Calvin Klein', 'unisex', 'mid', 'summer', 'daily', 6, NULL, NULL),
('Light Blue', 'Dolce&Gabbana', 'unisex', 'luxury', 'summer', 'daily', 7, NULL, 'Zara Aqua'),
('Acqua Universale', 'Mancera', 'unisex', 'luxury', 'spring', 'work', 9, NULL, 'CK One'),
('Wood Sage & Sea Salt', 'Jo Malone', 'unisex', 'luxury', 'summer', 'special', 8, NULL, 'Zara Aqua'),
('Aqua Universalis', 'Maison Francis', 'unisex', 'luxury', 'spring', 'daily', 10, NULL, 'CK One'),
('Zara Aqua', 'Zara', 'unisex', 'budget', 'summer', 'daily', 4, 'Light Blue - Dolce&Gabbana', NULL),
('Molecule 01', 'Escentric', 'unisex', 'mid', 'fall', 'work', 8, NULL, NULL),
('Neroli Portofino', 'Tom Ford', 'unisex', 'luxury', 'summer', 'special', 9, NULL, 'Zara Aqua'),
('Silver Mountain Water', 'Creed', 'unisex', 'luxury', 'winter', 'work', 11, NULL, 'Armaf Club de Nuit'),
('Rose Prick', 'Tom Ford', 'unisex', 'luxury', 'spring', 'evening', 10, NULL, 'Zara Rose');